FROM python:3.12-slim

WORKDIR /app

COPY docker/requirements-test.txt /app/requirements-test.txt

RUN pip install --no-cache-dir -r requirements-test.txt

COPY /app/functional_tests/ /app/functional_tests