FROM jenkins/jenkins

# Install dependencies
USER root
RUN apt-get update && \
apt-get install -y apt-transport-https \
ca-certificates \
curl \
gnupg \
lsb-release

# Install Docker
RUN curl -fsSL https://download.docker.com/linux/debian/gpg | gpg --dearmor -o /usr/share/keyrings/docker-archive-keyring.gpg && \
echo "deb [arch=arm64 signed-by=/usr/share/keyrings/docker-archive-keyring.gpg] https://download.docker.com/linux/debian $(lsb_release -cs) stable" | tee /etc/apt/sources.list.d/docker.list > /dev/null && \
apt-get update && \
apt-get install -y docker-ce

# Switch back to jenkins user
USER jenkins