version: '3'
services:
  jenkins:
    build: .
    privileged: true
    ports:
      - 8090:8080
    volumes:
      - jenkins_data:/var/jenkins_home_new
    depends_on:
      - docker
    networks:
      - jenkins-net

  docker:
    image: docker:dind
    privileged: true
    expose:
      - "2375"
    volumes:
      - docker_sock:/var/runs/docker.sock
    networks:
      - jenkins-net

volumes:
  jenkins_data:
  docker_sock:

networks:
  jenkins-net: