version: '3'
services:
  jenkins:
    build: .
    privileged: true
    ports:
      - 8090:8080
    volumes:
      - jenkins_data:/var/jenkins_home_new
    depends_on:
      - docker
    networks:
      - jenkins-net

  docker:
    image: docker:dind
    privileged: true
    expose:
      - 2375
    environment:
      - DOCKER_TLS_CERTDIR=
#    volumes:
#      - docker_sockts:/var/run/docker.sock
    networks:
      - jenkins-net

volumes:
  jenkins_data:
  docker_sockts:

networks:
  jenkins-net: